# Generated by Django 5.2.6 on 2025-11-11 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název cíle')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('goal_type', models.CharField(choices=[('SAVINGS', 'Úspory'), ('DEBT_PAYMENT', 'Splacení dluhu'), ('PURCHASE', 'Nákup'), ('EMERGENCY_FUND', 'Nouzový fond'), ('INVESTMENT', 'Investice'), ('OTHER', 'Jiné')], default='SAVINGS', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cílová částka')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aktuální částka')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Cílové datum')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktivní'), ('COMPLETED', 'Dokončeno'), ('PAUSED', 'Pozastaveno'), ('CANCELLED', 'Zrušeno')], default='ACTIVE', max_length=20)),
                ('icon', models.CharField(default='🎯', max_length=10)),
                ('color', models.CharField(default='#FF4742', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.financialgoal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
