# Generated by Django 5.2.8 on 2025-11-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialgoal',
            name='icon',
            field=models.CharField(default='target', max_length=10),
        ),
    ]
