# Generated by Django 5.2.1 on 2025-10-07 18:45

from django.db import migrations, models
import uuid

def generate_unique_username(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.username = f"user_{uuid.uuid4().hex[:8]}"
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='username'),
        ),
        migrations.RunPython(generate_unique_username),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=30, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='verified'),
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]