# Generated by Django 5.2.8 on 2025-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(default='CZK', max_length=3),
        ),
    ]
