# Generated by Django 5.2.8 on 2025-12-09 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_change_default_currency_to_czk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Název účtu')),
                ('account_type', models.CharField(choices=[('CHECKING', 'Běžný účet'), ('SAVINGS', 'Spořicí účet'), ('CASH', 'Hotovost'), ('CREDIT_CARD', 'Kreditní karta'), ('INVESTMENT', 'Investiční účet'), ('OTHER', 'Jiný')], default='CHECKING', max_length=20)),
                ('currency', models.CharField(choices=[('CZK', 'Česká koruna'), ('EUR', 'Euro'), ('USD', 'Americký dolar'), ('GBP', 'Britská libra')], default='CZK', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Počáteční zůstatek')),
                ('color', models.CharField(default='#8b5cf6', max_length=7)),
                ('icon', models.CharField(default='wallet', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_total', models.BooleanField(default=True, verbose_name='Zahrnout do celkového přehledu')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finanční účet',
                'verbose_name_plural': 'Finanční účty',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='accounts.financialaccount', verbose_name='Z účtu')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='accounts.financialaccount', verbose_name='Na účet')),
            ],
            options={
                'verbose_name': 'Převod mezi účty',
                'verbose_name_plural': 'Převody mezi účty',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
