# Generated by Django 5.2.8 on 2025-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_financialaccount_accounttransfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': 'Finanční účet', 'verbose_name_plural': 'Finanční účty'},
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='order',
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Výchozí účet'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Běžný účet'), ('SAVINGS', 'Spořicí účet'), ('CASH', 'Hotovost'), ('CREDIT', 'Kreditní karta'), ('INVESTMENT', 'Investiční účet'), ('OTHER', 'Ostatní')], default='CHECKING', max_length=20, verbose_name='Typ účtu'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='Barva'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='currency',
            field=models.CharField(default='CZK', max_length=3, verbose_name='Měna'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='icon',
            field=models.CharField(default='wallet', max_length=50, verbose_name='Ikona'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='include_in_total',
            field=models.BooleanField(default=True, verbose_name='Zahrnout do celkového zůstatku'),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.DeleteModel(
            name='AccountTransfer',
        ),
    ]
