# Generated by Django 5.2.6 on 2025-11-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('BOTH', 'Both')], default='EXPENSE', max_length=10),
        ),
    ]
