# Generated by Django 5.2.6 on 2025-11-11 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Název')),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INCOME', 'Příjem'), ('EXPENSE', 'Výdaj')], max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Denně'), ('WEEKLY', 'Týdně'), ('BIWEEKLY', 'Každé 2 týdny'), ('MONTHLY', 'Měsíčně'), ('QUARTERLY', 'Čtvrtletně'), ('YEARLY', 'Ročně')], max_length=20)),
                ('start_date', models.DateField(verbose_name='Datum začátku')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Datum konce')),
                ('next_due_date', models.DateField(verbose_name='Další splatnost')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktivní'), ('PAUSED', 'Pozastaveno'), ('COMPLETED', 'Dokončeno')], default='ACTIVE', max_length=20)),
                ('auto_create', models.BooleanField(default=False, verbose_name='Automaticky vytvářet transakce')),
                ('notify_before_days', models.IntegerField(default=3, verbose_name='Upozornit X dní předem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_auto_created', models.BooleanField(default=False)),
                ('recurring_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transactions.recurringtransaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_source', to='transactions.transaction')),
            ],
            options={
                'verbose_name_plural': 'Recurring transaction histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
