# Generated by Django 5.2.8 on 2025-12-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_financialaccount_accounttransfer'),
        ('transactions', '0003_recurringtransaction_recurringtransactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.financialaccount', verbose_name='Účet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts.financialaccount', verbose_name='Na účet'),
        ),
    ]
