# Generated by Django 5.2.8 on 2025-12-09 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_financialaccount_options_and_more'),
        ('transactions', '0004_transaction_account_transaction_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts.financialaccount', verbose_name='Cílový účet'),
        ),
    ]
